/**
 * Mapeo de Barrios a Comunas para Valledupar, Cesar, Colombia
 * Sincronizado DIRECTAMENTE con base de datos oficial CSV 2026/03/20
 */
export const GEOGRAFIA_VALLEDUPAR = {
    '1 de Mayo': '3',
    '11 de Noviembre': '1',
    '12 de Octubre': '2',
    '20 de Julio': '5',
    '20 de Marzo': '3',
    '25 de Diciembre': '3',
    '5 de Enero': '5',
    '5 de Noviembre': '2',
    '6 de Enero': '5',
    '7 de Agosto': '3',
    '8 de Diciembre': '4',
    '9 de Abril': '4',
    '9 de Marzo': '1',
    'Acacias': '4',
    'Acuarelas': '5',
    'Alamos Ii': '4',
    'Alamos Iii': '4',
    'Alfonzo Lopez': '6',
    'Alta Gracia': '1',
    'Alta Vista': '5',
    'Altos de Comfacesar': '5',
    'Altos de Don Alberto Viii': '5',
    'Altos de Pimiento': '5',
    'Altos de Ziruma I': '3',
    'Altos de Ziruma Ii': '3',
    'Altos de Ziruma Iii': '3',
    'Altos de Ziruma Iv': '3',
    'Altos del Rosario': '5',
    'Altos del Valle': '4',
    'Amaneceres del Valle': '2',
    'Ana Maria': '5',
    'Apartamentos Loft38': '5',
    'Argentina': '2',
    'Arizona': '5',
    'Atlantis': '5',
    'Azucar Buena': '5',
    'Balcones de Santa Helena': '5',
    'Bali': '5',
    'Bambu': '5',
    'Bambuterra': '5',
    'Barcelona': '5',
    'Barcelona Ii': '5',
    'Bariloche': '2',
    'Bella Vista': '5',
    'Bello Horizonte': '5',
    'Bilbao': '5',
    'Brasil': '2',
    'Brisas de la Popa': '5',
    'Buena Vista': '4',
    'Callejas del Norte': '5',
    'Campo Romero': '5',
    'Candelaria Norte': '5',
    'Candelaria Sur': '2',
    'Cantagiron': '5',
    'Casas de la Pradera': '4',
    'Casimiro Raul Maestre': '4',
    'Cañaguate': '6',
    'Ceiba Alta Gracia': '5',
    'Centro': '1',
    'Chile': '2',
    'Chimila': '6',
    'Chiriqui Norte': '3',
    'Ciceron Maestre': '4',
    'Citaringa Club House': '5',
    'Ciudad Jardin': '6',
    'Ciudad Tayrona': '5',
    'Ciudadela 450 Años': '4',
    'Ciudadela Comfacesar': '4',
    'Ciudadela Rosario Real': '5',
    'Club  House Ii': '5',
    'Club House': '5',
    'Colombia': '2',
    'Conjunto Aremasain': '6',
    'Conjunto Arizona': '5',
    'Conjunto Armonia': '3',
    'Conjunto Callejas': '5',
    'Conjunto Citaringa': '5',
    'Conjunto Granadillo': '5',
    'Conjunto Las Margaritas': '5',
    'Conjunto Las Orquideas': '5',
    'Conjunto Los Guayacanes Alcala': '3',
    'Conjunto Los Rosales': '5',
    'Conjunto Los Rosales I': '5',
    'Conjunto Los Rosales Ii': '5',
    'Conjunto Marcella Real': '5',
    'Conjunto Maria Isabella': '5',
    'Conjunto Pasadena': '6',
    'Conjunto Quintas del Country': '5',
    'Conjunto Residencial del Norte': '6',
    'Conjunto Residencial el Cerrito': '4',
    'Conjunto Rosas del Ateneo': '6',
    'Conjunto San Francisco de Asis': '2',
    'Conjunto San Pedro': '5',
    'Conjunto Santillana': '5',
    'Diomedez Daza': '5',
    'Divino Niño': '5',
    'Don Alberto': '5',
    'Don Alberto V': '5',
    'Don Alberto Vi': '5',
    'Don Alberto Vii': '5',
    'Don Carmelo': '3',
    'Don Felipe': '3',
    'Don Miguel': '5',
    'Doña Clara': '2',
    'Doña Fina': '5',
    'Dundakare': '5',
    'Edgardo Pupo': '4',
    'Efrain Quintero': '3',
    'Emanuel': '3',
    'Eneal': '5',
    'Enrique Pupo': '5',
    'Entresierras': '3',
    'Florencia': '2',
    'Flores de Maria': '4',
    'Francisco Javier': '5',
    'Francisco Paula Santander': '4',
    'Francisco el Hombre': '5',
    'Fundadores': '4',
    'Futuro de Los Niños': '5',
    'Gaitan': '1',
    'Galan': '4',
    'Garupal': '5',
    'Gerizim': '4',
    'Guajira': '6',
    'Guatapuri': '1',
    'Ichagua': '5',
    'Iracal': '5',
    'Jorge Dangond': '4',
    'Kenedy': '1',
    'Las Cabañas': '4',
    'Las Cayenas': '5',
    'Las Delicias': '1',
    'Las Flores': '5',
    'Las Manuelitas': '3',
    'Las Palmas': '1',
    'Las Palmeras': '4',
    'Las Trinitarias': '5',
    'Leandro Diaz': '3',
    'Limonar': '4',
    'Loperena': '1',
    'Los  Campanos': '6',
    'Los Alamos': '3',
    'Los Angeles': '6',
    'Los Caciques': '4',
    'Los Cañaguates': '5',
    'Los Cocos': '2',
    'Los Corales': '5',
    'Los Cortijos': '5',
    'Los Guasimales': '5',
    'Los Milagros': '2',
    'Los Musicos': '5',
    'Manantial': '4',
    'Mar del Pata': '2',
    'Mareigua': '3',
    'Maria Camila': '4',
    'Maria Camila Norte': '5',
    'Maria Daniela': '6',
    'Maria Valeria': '4',
    'Mayales Aeropuerto': '3',
    'Mayales Etapa I': '2',
    'Mirador de la Sierra I': '5',
    'Mirador de la Sierra Ii': '5',
    'Mirador de la Sierra Iii': '5',
    'Mirador de la Sierra Iv': '5',
    'Montecarlo': '2',
    'Norte de Don Alberto Ix': '5',
    'Novalito': '6',
    'Nueva Colombia': '1',
    'Nueva Esperanza': '5',
    'Nuevo Amanecer': '5',
    'Nuevo Milenio': '3',
    'Obrero': '6',
    'Ogb': '3',
    'Oriente  de Callejas': '5',
    'Pablo Vi': '1',
    'Palmares I': '2',
    'Palmares Ii': '2',
    'Palmeto': '5',
    'Panama': '2',
    'Panama Ii': '2',
    'Paraiso I': '1',
    'Paraiso Ii': '1',
    'Parque la Primavera la Primavera': '3',
    'Pescadito': '1',
    'Pontevedra': '6',
    'Populandia': '4',
    'Portal del Cerrito': '4',
    'Portal del Rosario': '5',
    'Portobelo': '5',
    'Quintas del Rosario': '5',
    'Rafael Escalona': '4',
    'Reserva Upar': '5',
    'Rincon de Ziruma': '3',
    'Rocas del Valle': '5',
    'Rosario Norte I': '5',
    'Rosario Norte Ii': '5',
    'Rueda': '3',
    'Sabanas del Valle': '4',
    'San Antonio': '3',
    'San Carlos': '6',
    'San Clemente': '6',
    'San Fernando': '2',
    'San Francisco': '3',
    'San Isidro': '5',
    'San Jeronimo': '4',
    'San Joaquin': '6',
    'San Jorge': '1',
    'San Juan': '2',
    'San Marino': '4',
    'San Martin': '3',
    'San Vicente': '1',
    'Santa Ana': '1',
    'Santa Rita': '2',
    'Santa Rosa': '2',
    'Santa Rosalia': '6',
    'Santo  Domingo': '1',
    'Serranilla': '6',
    'Sicarare': '1',
    'Simon Bolivar': '2',
    'Terranova': '5',
    'Terrazza 64': '3',
    'Tierra Prometida': '3',
    'Tobias Daza': '4',
    'Torres Don Jose': '4',
    'Torres de Villa del Rosario': '3',
    'Torres del Norte': '5',
    'Toscana': '2',
    'Urb Casa Blanca': '5',
    'Urb Las Marias': '5',
    'Urb Mayales': '2',
    'Urb Miraflores': '4',
    'Urb la Sabana': '5',
    'Urb. George Dangond': '2',
    'Urb. Lorenzo Morales': '3',
    'Urb. Luis Carlos Galan': '2',
    'Urb. Maria Paula': '4',
    'Urb. Nando Marin': '3',
    'Urb. Rosamery': '2',
    'Urb. Santa Rosa': '5',
    'Urbanizacion Lindaraja': '4',
    'Valle Meza': '3',
    'Valparaiso': '2',
    'Villa Algenia': '4',
    'Villa Andres': '5',
    'Villa Arcadia': '4',
    'Villa Carel': '5',
    'Villa Castro': '2',
    'Villa Clara': '2',
    'Villa Concha': '5',
    'Villa Consuelo': '5',
    'Villa Corelca': '4',
    'Villa Dariana': '4',
    'Villa Elvia': '5',
    'Villa Erika': '5',
    'Villa Fanny': '5',
    'Villa Fuente': '3',
    'Villa Haydith': '3',
    'Villa Janeth': '5',
    'Villa Leonor': '3',
    'Villa Ligia I': '5',
    'Villa Ligia Ii': '5',
    'Villa Ligia Iii': '5',
    'Villa Ligia Iv': '5',
    'Villa Lucy': '5',
    'Villa Luz': '4',
    'Villa Magdala': '4',
    'Villa Maruamake': '4',
    'Villa Mirian': '4',
    'Villa Monica': '5',
    'Villa Olga': '3',
    'Villa Rosa': '5',
    'Villa Taxi': '4',
    'Villa Tayrona': '5',
    'Villa Uribe': '3',
    'Villa Valeria': '5',
    'Villa del Rosario': '2',
    'Villa del Rosario Norte': '6',
    'Villalba': '5',
    'Villas de Catalina': '4',
    'Vive Alto': '2',
    'Zapato en Mano': '1',
    'el Amparo': '5',
    'el Carmen': '1',
    'el Cerrito': '4',
    'el Eden': '3',
    'el Hogar': '4',
    'el Oasis': '3',
    'el Paramo': '3',
    'el Prado': '3',
    'el Progreso': '4',
    'el Refugio': '5',
    'el Rocio': '4',
    'la Castellana': '5',
    'la Ceiba': '5',
    'la Esperanza': '5',
    'la Esperanza Oriente': '1',
    'la Felicidad': '3',
    'la Floresta': '4',
    'la Fontana Urb la Fontana Ii': '4',
    'la Fortuna': '5',
    'la Garita': '1',
    'la Granja': '1',
    'la Nevada': '5',
    'la Popa': '5',
    'la Primavera 1': '3',
    'la Rioja': '5',
    'la Rivera': '2',
    'la Victoria': '4',
};

export const LISTA_BARRIOS = Object.keys(GEOGRAFIA_VALLEDUPAR).sort();

export const getComunaByBarrio = (barrio) => {
    if (!barrio) return '';

    // Búsqueda exacta primero
    if (GEOGRAFIA_VALLEDUPAR[barrio]) return GEOGRAFIA_VALLEDUPAR[barrio];

    // Búsqueda insensible a mayúsculas
    const normalizedInput = barrio.toLowerCase().trim();
    const foundBarrio = Object.keys(GEOGRAFIA_VALLEDUPAR).find(
        key => key.toLowerCase() === normalizedInput
    );

    return foundBarrio ? GEOGRAFIA_VALLEDUPAR[foundBarrio] : '';
};
